version: '3'

services:
  db:
    image: postgres:9.6.5
    volumes:
    - postgres_data:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    build: .
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    working_dir: /code/src
    command: pipenv run celery -A app worker -l info
    volumes:
      - .:/code/
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    working_dir: /code/src
    command: pipenv run celery -A app beat -l info
    volumes:
      - .:/code/
    depends_on:
      - db
      - redis

volumes:
  postgres_data: