name: Deploy & Validator Test

on:
  pull_request:
    branches: master
    types: [open, edited, reopened]

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Requirements
      run: sudo apt-get install docker.io git curl
    - name: Checkout HEAD
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Deploy to Staging
      run: git push staging master -f
    - name: Test via Validator
      run: |
        RESULTS="$(docker run -e DOMAIN=https://stellar-anchor-server-staging.herokuapp.com msfeldstein/transfer-server-validator)"
        PR_NUMBER=$(echo $GITHUB_REF | grep -o '[0-9]\+')
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
            "body": "**${{ github.workflow }}**. \n\n'\""$RESULTS\""'
          }'
